-- CREATE DATABASE HOSPITALDB
CREATE DATABASE IF NOT EXISTS HospitalDB;

-- SHOW DATABASES
SHOW DATABASES;

-- SWITCH DATABASE
USE HospitalDB;

-- CREATE PATIENTS TABLE
CREATE TABLE PATIENTS(
PATIENT_ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(255) NOT NULL,
GENDER VARCHAR(10) CHECK (GENDER IN('Male','Female','other')),
DOB DATE NOT NULL,
PHONE BIGINT UNIQUE KEY,
ADDRESS VARCHAR(255));

-- CREATE DEPARTMENTS TABLE
CREATE TABLE DEPARTMENTS(
DEPARTMENT_ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(255) UNIQUE KEY NOT NULL,
FLOOR INT CHECK(FLOOR>0));

-- CREATE DOCTORS TABLE
CREATE TABLE DOCTORS(
DOCTOR_ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(255)NOT NULL,
SPECIALIZATION VARCHAR(255) NOT NULL,
PHONE BIGINT,
DEPARTMENT_ID INT,
FOREIGN KEY(DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID));

-- CREATE APPOINTMENTS TABLE
CREATE TABLE APPOINTMENTS(
APPOINTMENT_ID INT AUTO_INCREMENT PRIMARY KEY,
PATIENT_ID INT NOT NULL,
DOCTOR_ID INT NOT NULL,
APPOINTMENT_DATE DATE NOT NULL,
STATUS VARCHAR(255) NOT NULL CHECK(STATUS IN('SCHEDULED','COMPLETED','CANCELLED')),
FOREIGN KEY(PATIENT_ID)REFERENCES PATIENTS(PATIENT_ID),
FOREIGN KEY(DOCTOR_ID)REFERENCES DOCTORS(DOCTOR_ID));

-- CREATE BILLS TABLE
CREATE TABLE BILLS(
BILL_ID INT AUTO_INCREMENT PRIMARY KEY,
PATIENT_ID INT NOT NULL,
AMOUNT INT NOT NULL CHECK(AMOUNT>=0),
BILL_DATE DATE NOT NULL,
PAYMENT_STATUS VARCHAR(255) CHECK(PAYMENT_STATUS IN('PAID','PENDING','OVERDUE')),
FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID));

-- SHOW TABLES
SHOW TABLES;

/* Tables_in_hospitaldb
appointments
bills
departments
doctors
patients
*/